# yaml-language-server: $schema=../automated_security_helper/schemas/AshConfig.json
project_name: automated-security-helper
fail_on_findings: true
ash_plugin_modules:
  - automated_security_helper.plugin_modules.ash_ferret_plugins
# ash_plugin_modules:
#   - automated_security_helper.plugin_modules.ash_aws_plugins
#   - automated_security_helper.plugin_modules.ash_trivy_plugins
external_reports_to_include: []
global_settings:
  severity_threshold: MEDIUM
  suppressions:
    - path: tests/integration/cli/test_mcp_file_tracking_integration.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/test_mcp_integration_simple.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/test_mcp_integration.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: tests/integration/cli/conftest.py
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive.
    - path: pyproject.toml
      rule_id: SECRET-BASE64-HIGH-ENTROPY-STRING
      reason: This is the project configuration. Findings of this type are false positives.
    - path: automated_security_helper/utils/subprocess_utils.py
      rule_id: python.lang.compatibility.python36.python36-compatibility-Popen1
      reason: This package requires Python3.10 or greater.
    - path: automated_security_helper/utils/subprocess_utils.py
      rule_id: python.lang.compatibility.python36.python36-compatibility-Popen2
      reason: This package requires Python3.10 or greater.
    - path: tests/unit/plugin_modules/ash_aws_plugins/test_cloudwatch_logs_reporter*
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, dummy test data and not an actual secret.
    - path: automated_security_helper/plugin_modules/ash_ferret_plugins/DEVELOPMENT.md
      rule_id: SECRET-SECRET-KEYWORD
      line_start: 501
      line_end: 501
      reason: Documentation example showing the SECRET-SECRET-KEYWORD detection pattern.
    - path: automated_security_helper/plugin_modules/ash_ferret_plugins/ferret_scanner.py
      rule_id: B404
      line_start: 9
      line_end: 9
      reason: Subprocess module required — ferret-scan is an external CLI tool invoked via subprocess with list args (no shell=True).
    - path: automated_security_helper/plugin_modules/ash_ferret_plugins/ferret_scanner.py
      rule_id: B603
      line_start: 410
      line_end: 435
      reason: Subprocess calls use list args (no shell=True) with validated inputs. ferret-scan binary path comes from shutil.which().
    - path: automated_security_helper/plugin_modules/ash_ferret_plugins/ferret_scanner.py
      rule_id: B607
      line_start: 410
      line_end: 435
      reason: Partial executable path resolved via shutil.which() in validate_plugin_dependencies(). Standard ASH scanner pattern.
    - path: scripts/generate_test_docx.py
      rule_id: B311
      line_start: 1
      line_end: 203
      reason: Standard random is intentional — generates synthetic test data with random.seed(42) for reproducibility, not used for security/crypto.
    - path: tests/unit/plugin_modules/ash_ferret_plugins/conftest.py
      rule_id: SECRET-SECRET-KEYWORD
      line_start: 146
      line_end: 146
      reason: False positive — SETTING = "placeholder" uses a neutral variable name.
    - path: scripts/generate_test_docx.py
      rule_id: SECRET-HEX-HIGH-ENTROPY-STRING
      line_start: 175
      line_end: 177
      reason: False positive — runtime-generated synthetic credit card numbers from seeded random for test data.
    - path: .github/workflows/run-ash-security-scan.yml
      rule_id: yaml.github-actions.security.run-shell-injection.run-shell-injection
      reason: Troubleshooting swapping from direct injection to evaluating interpolated env vars
      expiration: "2026-06-01"
    - path: tests/**/*.py
      rule_id: B101
      reason: Assert usage expected with Pytest
    - path: tests/utils/*.py
      rule_id: B311
      reason: Test facilities and tooling used to generate randomness during testing.
    - path: tests/unit/utils/*.py
      rule_id: B108
      reason: Temp file path as string, not actual temp dir usage.
    - path: tests/**/*.py
      rule_id: B404
      reason: Subprocess module used across test suite due to the nature of ASH itself being a tool orchestrator. These instances are in test suites and not in the code used at runtime.
    - path: tests/**/*.py
      rule_id: B603
      reason: Subprocess module used across test suite due to the nature of ASH itself being a tool orchestrator. These instances are in test suites and not in the code used at runtime.
    - path: tests/**/*.py
      rule_id: B607
      reason: Mocking and other test mechanisms. These instances are in test suites and not in the code used at runtime.
    - path: docs/content/docs/plugins/aws/index.md
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, not an actual secret
    - path: docs/content/docs/plugins/development-guide.md
      rule_id: SECRET-SECRET-KEYWORD
      reason: False positive, not an actual secret
    - path: docs/content/docs/testing/examples/*
      reason: Documentation with test code examples focused on brevity.
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/*.*"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/reports/*.json"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "SECRET-HEX-HIGH-ENTROPY-STRING"
      path: ".ash/ash_output*/scanners/*.json"
      reason: "False positive - ASH output files contain hashes and IDs that trigger entropy detection"
    - rule_id: "python.lang.compatibility.python36.python36-compatibility-Popen1"
      path: automated_security_helper/utils/subprocess_utils.py
      reason: "False positive - ASH requires Python 3.10+, compatibility with Python3.6 and less is not required"
    - rule_id: "python.lang.compatibility.python36.python36-compatibility-Popen2"
      path: automated_security_helper/utils/subprocess_utils.py
      reason: "False positive - ASH requires Python 3.10+, compatibility with Python3.6 and less is not required"
    - rule_id: SECRET-SECRET-KEYWORD
      path: automated_security_helper/utils/secret_masking.py
      reason: "False positive - Secret found message string"
      line_start: 37
      line_end: 37
    - rule_id: SECRET-SECRET-KEYWORD
      path: automated_security_helper/utils/secret_masking.py
      reason: "False positive - Secret found message string"
      line_start: 46
      line_end: 46
    - rule_id: SECRET-SECRET-KEYWORD
      path: tests/unit/utils/test_secret_masking.py
      reason: "False positive - Multiple ocurrences of the keyword due to the nature of the test suite"
    - rule_id: SECRET-BASE64-HIGH-ENTROPY-STRING
      path: tests/unit/utils/test_secret_masking.py
      reason: "False positive - Multiple ocurrences of the keyword due to the nature of the test suite"
    - path: "terraform/modules/**"
      rule_id: terraform.lang.security.iam.no-iam-resource-exposure.no-iam-resource-exposure
      reason: "IAM resource exposure rules are reviewed and accepted for these modules"
    - path: "terraform/modules/**"
      rule_id: terraform.lang.security.iam.no-iam-data-exfiltration.no-iam-data-exfiltration
      reason: "IAM data exfiltration rules are reviewed and accepted for these modules"
    - path: "terraform/modules/**"
      rule_id: terraform.aws.security.aws-lambda-x-ray-tracing-not-active.aws-lambda-x-ray-tracing-not-active
      reason: "X-Ray tracing not required for these Lambda functions"
    - path: "terraform/modules/**"
      rule_id: terraform.aws.security.aws-lambda-environment-unencrypted.aws-lambda-environment-unencrypted
      reason: "Lambda environment encryption reviewed and accepted"
    - path: "terraform/modules/**"
      rule_id: terraform.lang.security.iam.no-iam-priv-esc-funcs.no-iam-priv-esc-funcs
      reason: "IAM privilege escalation rules are reviewed and accepted for these modules"
    - path: "CLIENT_DOCUMENTATION.txt"
      rule_id: SECRET-SECRET-KEYWORD
      reason: "False positive in documentation file"
    - rule_id: SECRET-SECRET-KEYWORD
      path: CLIENT_DOCUMENTATION.txt
      line_start: 1894
      line_end: 1894
      reason: "False positive - Client documentation, not an actual secret"
    - rule_id: terraform.lang.security.iam.no-iam-data-exfiltration.no-iam-data-exfiltration
      path: terraform/modules/datazone-blueprints/main.tf
      line_start: 101
      line_end: 101
      reason: "Accepted risk - secretsmanager:GetSecretValue scoped by ResourceTag condition on AmazonDataZoneDomain"
    - rule_id: terraform.lang.security.iam.no-iam-data-exfiltration.no-iam-data-exfiltration
      path: terraform/modules/datazone-blueprints/main.tf
      line_start: 153
      line_end: 153
      reason: "Accepted risk - S3 actions scoped by aws:ResourceAccount condition limiting to same account"
    - rule_id: terraform.lang.security.iam.no-iam-data-exfiltration.no-iam-data-exfiltration
      path: terraform/modules/datazone-domain-units/main.tf
      line_start: 106
      line_end: 106
      reason: "Accepted risk - KMS actions (Decrypt/GenerateDataKey) require Resource=* as key ARNs are dynamic at deploy time"
    - rule_id: terraform.lang.security.iam.no-iam-data-exfiltration.no-iam-data-exfiltration
      path: terraform/modules/emr-on-eks/main.tf
      line_start: 49
      line_end: 49
      reason: "False positive - S3 actions already scoped to specific bucket ARNs"
    - rule_id: terraform.lang.security.iam.no-iam-resource-exposure.no-iam-resource-exposure
      path: terraform/modules/datazone-account-association/main.tf
      line_start: 53
      line_end: 53
      reason: "Accepted risk - DataZone cross-account role requires broad LakeFormation Grant/Revoke permissions by design"
    - rule_id: terraform.lang.security.iam.no-iam-resource-exposure.no-iam-resource-exposure
      path: terraform/modules/datazone-blueprints/main.tf
      line_start: 290
      line_end: 290
      reason: "False positive - iam:PassRole already scoped to specific query execution role ARN"
    - rule_id: terraform.lang.security.iam.no-iam-resource-exposure.no-iam-resource-exposure
      path: terraform/modules/datazone-role-policy-automation/main.tf
      line_start: 83
      line_end: 83
      reason: "Accepted risk - iam:AttachRolePolicy scoped to datazone_usr_role_* with PolicyARN condition"
    - rule_id: terraform.lang.security.iam.no-iam-priv-esc-funcs.no-iam-priv-esc-funcs
      path: terraform/modules/datazone-role-policy-automation/main.tf
      line_start: 83
      line_end: 83
      reason: "False positive - iam:AttachRolePolicy constrained to datazone_usr_role_* resources with ArnEquals condition limiting to a single KMS policy ARN"
    - rule_id: CKV_AWS_290
      path: terraform/modules/datazone-account-association/main.tf
      line_start: 42
      line_end: 42
      reason: "Accepted risk - DataZone cross-account role requires broad datazone:* and LakeFormation permissions by design"
    - rule_id: CKV_AWS_355
      path: terraform/modules/datazone-account-association/main.tf
      line_start: 42
      line_end: 42
      reason: "Accepted risk - DataZone cross-account role requires Resource=* for datazone and LakeFormation actions"
    - rule_id: CKV_AWS_290
      path: terraform/modules/datazone-domain-units/main.tf
      line_start: 61
      line_end: 61
      reason: "False positive - DataZone write actions already scoped to domain/* ARN"
    - rule_id: CKV_AWS_355
      path: terraform/modules/datazone-domain-units/main.tf
      line_start: 61
      line_end: 61
      reason: "False positive - DataZone actions already scoped to domain/* ARN"
    - rule_id: CKV_AWS_290
      path: terraform/modules/datazone-role-policy-automation/main.tf
      line_start: 72
      line_end: 72
      reason: "Accepted risk - iam:AttachRolePolicy scoped to datazone_usr_role_* with PolicyARN condition"
    - rule_id: CKV_AWS_355
      path: terraform/modules/datazone-role-policy-automation/main.tf
      line_start: 72
      line_end: 72
      reason: "Accepted risk - iam:AttachRolePolicy scoped to datazone_usr_role_* with PolicyARN condition"
    - rule_id: CKV_AWS_116
      path: terraform/modules/datazone-blueprints/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda with built-in retry logic; DLQ not warranted"
    - rule_id: CKV_AWS_116
      path: terraform/modules/datazone-domain-units/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda with built-in retry logic; DLQ not warranted"
    - rule_id: CKV_AWS_116
      path: terraform/modules/datazone-project-profile-v2/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda with built-in retry logic; DLQ not warranted"
    - rule_id: CKV_AWS_116
      path: terraform/modules/datazone-role-policy-automation/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda with built-in retry logic; DLQ not warranted"
    - rule_id: CKV_AWS_117
      path: terraform/modules/datazone-blueprints/main.tf
      reason: "Accepted risk - Lambda only calls AWS APIs (DataZone); no VPC resources needed"
    - rule_id: CKV_AWS_117
      path: terraform/modules/datazone-domain-units/main.tf
      reason: "Accepted risk - Lambda only calls AWS APIs (DataZone, S3, KMS); no VPC resources needed"
    - rule_id: CKV_AWS_117
      path: terraform/modules/datazone-project-profile-v2/main.tf
      reason: "Accepted risk - Lambda only calls AWS APIs (DataZone); no VPC resources needed"
    - rule_id: CKV_AWS_117
      path: terraform/modules/datazone-role-policy-automation/main.tf
      reason: "Accepted risk - Lambda only calls AWS APIs (IAM); no VPC resources needed"
    - rule_id: CKV_AWS_173
      path: terraform/modules/datazone-role-policy-automation/main.tf
      reason: "Accepted risk - Environment variables (POLICY_ARN, DOMAIN_ID) are non-sensitive resource identifiers, not secrets"
    - rule_id: terraform.aws.security.aws-lambda-environment-unencrypted.aws-lambda-environment-unencrypted
      path: terraform/modules/datazone-role-policy-automation/main.tf
      line_start: 48
      line_end: 48
      reason: "Accepted risk - Environment variables (POLICY_ARN, DOMAIN_ID) are non-sensitive resource identifiers, not secrets"
    - rule_id: terraform.aws.security.aws-lambda-x-ray-tracing-not-active.aws-lambda-x-ray-tracing-not-active
      path: terraform/modules/datazone-blueprints/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda; X-Ray tracing not required"
    - rule_id: terraform.aws.security.aws-lambda-x-ray-tracing-not-active.aws-lambda-x-ray-tracing-not-active
      path: terraform/modules/datazone-domain-units/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda; X-Ray tracing not required"
    - rule_id: terraform.aws.security.aws-lambda-x-ray-tracing-not-active.aws-lambda-x-ray-tracing-not-active
      path: terraform/modules/datazone-project-profile-v2/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda; X-Ray tracing not required"
    - rule_id: terraform.aws.security.aws-lambda-x-ray-tracing-not-active.aws-lambda-x-ray-tracing-not-active
      path: terraform/modules/datazone-role-policy-automation/main.tf
      reason: "Accepted risk - Low-frequency automation Lambda; X-Ray tracing not required"
  ignore_paths:
    - path: "**/.venv/**"
      reason: Virtual environment, not committed, only 3p content
    - path: "tests/test_data/**"
      reason: This is test data that is used during unit testing only and is not part of the core application.
    - path: "automated_security_helper/assets/ASH_COMMIT*"
      reason: This file is generated by the build process and does not contain any secrets or sensitive information.
    - path: "tests/pytest-temp"
      reason: This is temporary data that is generated during unit testing only and is not part of the core application.
    - path: "**/automated_security_helper/schemas/AshAggregatedResults.json"
      reason: This file is generated by a corresponding Pydantic model and does not contain any secrets or sensitive information. Findings on this file are false positives and should be addressed on the related Pydantic models, not on this JSON file.
    - path: "**/automated_security_helper/schemas/AshConfig.json"
      reason: This file is generated by a corresponding Pydantic model and does not contain any secrets or sensitive information. Findings on this file are false positives and should be addressed on the related Pydantic models, not on this JSON file.
    - path: "terraform/examples/emr-eks/**"
      reason: EMR/EKS example infrastructure not in scope for this scan.
    - path: "terraform/assets/emr/**"
      reason: EMR assets not in scope for this scan.
    - path: "terraform/modules/eks/**"
      reason: EKS module not in scope for this scan.
    - path: "terraform/modules/emr-on-eks/templates/**"
      reason: EMR on EKS pod templates are managed by Spark/EMR runtime; K8s security context not applicable.
    - rule_id: generic.secrets.security.detected-aws-account-id.detected-aws-account-id
      path: terraform/modules/datazone-account-association/README.md
      reason: "Informational - AWS account IDs in documentation examples are not sensitive"
reporters:
  security-hub:
    enabled: false
  # cloudwatch-logs:
  #   enabled: false
  #   options:
  #     aws_region: !ENV ${AWS_REGION:None}
  #     log_group_name: !ENV ${ASH_CLOUDWATCH_LOG_GROUP:None}
  # s3:
  #   enabled: false
  #   options:
  #     aws_region: !ENV ${AWS_REGION:None}
  #     bucket_name: !ENV ${ASH_S3_BUCKET_NAME:None}
  #     bucket_prefix: !ENV ${ASH_S3_BUCKET_PREFIX:None}
  csv:
    enabled: true
  cyclonedx:
    enabled: true
  flat-json:
    enabled: true
  html:
    enabled: true
  junitxml:
    enabled: true
  markdown:
    enabled: true
    options:
      include_detailed_findings: true
      include_findings_table: false
      include_summary: true
      max_detailed_findings: 20
      top_hotspots_limit: 10
      use_collapsible_details: true
  ocsf:
    enabled: true
  sarif:
    enabled: true
  text:
    enabled: true
  spdx:
    enabled: false
  yaml:
    enabled: false
  gitlab-sast:
    enabled: true
scanners:
  bandit:
    enabled: true
    options:
      confidence_level: all
      ignore_nosec: false
      config_file: .ash/bandit.yaml
  cdk-nag:
    enabled: true
    options:
      nag_packs:
        AwsSolutionsChecks: true
        HIPAASecurityChecks: true
        NIST80053R4Checks: true
        NIST80053R5Checks: true
        PCIDSS321Checks: true
  cfn-nag:
    enabled: true
  checkov:
    enabled: true
    options:
      frameworks:
        - all
      additional_formats: []
      skip_path: []
      config_file: .ash/.checkov.yaml
      severity_threshold: LOW
  detect-secrets:
    enabled: true
  npm-audit:
    enabled: true
  grype:
    enabled: true
    options:
      config_file: .ash/.grype.yaml
  opengrep:
    enabled: true
  semgrep:
    enabled: true
  syft:
    enabled: true
  ferret-scan:
    enabled: true
    options:
      confidence_levels: "high"
      checks: "CREDIT_CARD,SSN,PASSPORT,EMAIL,PHONE,SECRETS"
      recursive: true
converters:
  archive:
    enabled: true
  jupyter:
    enabled: true
